### ISSUE TITLE
Combine with default resolver (example)

### ISSUE THREAD

**Issue by jagregory** [Jmeyering/react-docgen-annotation-resolver#2]
Not sure if this is worth mentioning in the README, but I found it useful to combine the output of this resolver with the default docgen resolver; this approach allows regular React components to be documented as expected (PropTypes and all), and styled-components when used with the `@component` annotation to flow through this resolver and at least appear in the styleguide.

```js
const { findAllExportedComponentDefinitions } = require("react-docgen").resolver;
const annotationResolver = require("react-docgen-annotation-resolver").default;

module.exports = {
  resolver: (ast, recast) => [
    ...findAllExportedComponentDefinitions(ast, recast),
    ...annotationResolver(ast, recast)
  ]
};
```

Thanks for creating this extension!

**Comment by Jmeyering** [comment]
This is merged into react-styleguidist core.
