### ISSUE TITLE
Integrate into react-docgen

### ISSUE THREAD

**Issue by danez** [Jmeyering/react-docgen-annotation-resolver#29]
Hi @Jmeyering,

I like the idea of this resolver and thought it might be a good thing to have out-of-the-box in react-docgen. I'm currently preparing for version 6 of react-docgen, which will come with a lot of breaking changes, so I was wondering if this is also a good point to embrace all the excellent community build things around react-docgen.
I'm not sure if integrating this into the core of `react-docgen` is the right approach and okay with you, but I would be interested to hear from you what you think?

Other ideas I was playing around with in my head are creating a github org to serve as a place for all things around react-docgen related. But then I was unsure as simply integrating packages into the react-docgen monorepo, would have more benefits in terms of maintenance overhead.

Anyway, I just wanted to ask what you think about all of this in general and if you think this would be a good fit to come with `react-docgen` out-of-the-box in one or the other way?

**Comment by Jmeyering** [comment]
Hey Daniel! Thanks so much for reaching out. I'm totally fine with react-docgen using this functionality in react-docgen itself. I think it's a great idea!

I tend to prefer native support over a github organization to store libraries and such but would support that idea as well if it's the direction you would prefer to go.

Let me know if you need any assistance with anything.

**Comment by danez** [comment]
I added a new resolver to react-docgen directly, which detects annotations on components. I decided though to go a different route, than this resolver. Your resolver checks for annotations on exports, whereas the [one I integrated now](https://github.com/reactjs/react-docgen/pull/743) checks on any component definition, exported or not.

Thanks for the idea and inspiration for this resolver.
