### ISSUE TITLE
Needs npm publish?

### ISSUE THREAD

**Issue by jbellsey** [Jmeyering/react-docgen-annotation-resolver#4]
Hi - it looks like the source on Github is out of sync with the NPM repo by one commit.

In particular, the line on Github has some extra tools...

```js
components.push(docgenUtils.resolveToValue(resolveHOC(definition)));
```

...that aren't in NPM:

```js
components.push(definition);
```

I'll fork it for now, because this is great work! (Using it to annotate [Emotion](https://emotion.sh) components.)

**Comment by Jmeyering** [comment]
Thanks for reporting this! I just release v1.1.0 to npm.
