### ISSUE TITLE
Getting `RangeError: Maximum call stack size exceeded` with react-docgen@5.0.0-beta.1

### ISSUE THREAD

**Issue by donysukardi** [Jmeyering/react-docgen-annotation-resolver#9]
I added the custom resolver and i'm getting `RangeError: Maximum call stack size exceeded` when running react-docgen against function components and styled-components

```js
const { findAllExportedComponentDefinitions } = require('react-docgen').resolver;
const annotationResolver = require('react-docgen-annotation-resolver');

const resolver = (ast, recast) => [
  ...findAllExportedComponentDefinitions(ast, recast),
  ...annotationResolver(ast, recast),
]
```

![image](https://user-images.githubusercontent.com/410792/68568003-5c18f880-0495-11ea-88ab-3604b8111a5a.png)

Sample component:

```jsx
import React, { Component } from 'react';
import styled from 'styled-components';
import PropTypes from 'prop-types';

/**
 * General component description.
 */
const MyComponent = styled.button``;

MyComponent.propTypes = {
  /**
   * Description of prop "foo".
   */
  foo: PropTypes.number,
  /**
   * Description of prop "bar" (a custom validation function).
   */
  bar: function(props, propName, componentName) {
    // ...
  },
  baz: PropTypes.oneOfType([
    PropTypes.number,
    PropTypes.string
  ]).isRequired,
};

MyComponent.defaultProps = {
  foo: 42,
  bar: 21
};

/**
 * @component
 */
export default MyComponent;
```

**Comment by andrew-t-james** [comment]
I am getting the same `RangeError: Maximum call stack size exceeded` with react-docgen@^5.0.0. 
Possible break coming from https://github.com/reactjs/react-docgen/releases under the 5.0.0 section. 

> When we detect HOC react-docgen now assumes that the first argument to the HOC is the component. Previously we assumed the last argument is the component, but nearly all implementations of HOC which have multiple arguments have the component as the first argument.
